yaourt -S albert \
alsa-utils \
amor \
android-sdk \
android-tools \
arc-gtk-theme \
ardour \
arduino \
argon \
ark \
atom \
audacity \
autogen \
automoc4 \
baobab \
bdf-unifont \
bin86 \
bind-tools \
blueman-git \
bower \
cheese \
chromium \
clang \
cloog \
composer \
cpupower \
cronie \
cython \
docker-compose \
doxygen \
eog \
ethtool \
evince \
filezilla \
firefox \
flashplugin \
gambas3-gb-form \
gambas3-gb-gtk \
gedit \
gendesk \
gimagereader \
gitkraken \
gnome-calculator \
gnome-disk-utility \
gnome-system-monitor \
go \
google-chrome \
gparted \
grub-customizer \
gstreamer0.10-base-plugins \
gstreamer0.10-good-plugins \
gtk2-perl \
gtk-xfce-engine \
guitarix2 \
hardening-wrapper \
hardinfo \
help2man \
htop \
inkscape \
kodi \
ksysguard \
leagueoflegends-git \
lib32-gtk3 \
lib32-jansson \
lib32-js17 \
lib32-json-c \
libmediainfo \
libreoffice-fresh-fr \
livewallpaper \
lximage-qt \
lxqt-about \
lxqt-admin \
lxqt-config \
lxqt-openssh-askpass \
lxqt-panel \
lxqt-policykit \
lxqt-powermanagement \
lxqt-qtplugin \
lxqt-runner \
lxqt-session \
lxqt-sudo \
mariadb \
megasync \
memtest86+ \
mencoder \
meteor-js \
mlocate \
multisystem \
musicbrainz \
network-manager-applet \
networkmanager-openvpn \
ninja \
nmap \
nodejs-ionic \
ocrfeeder \
openldap \
openssh \
optiprime \
orage \
packagekit \
perl-file-sharedir \
perl-module-build \
perl-net-sdp \
php-apache \
php-gd \
php-mcrypt \
phpmd \
phpmyadmin \
php-pear \
picard \
pip \
playonlinux \
pocketsphinx \
powerline-fonts \
ppl \
pulseaudio-bluetooth \
pulseaudio-jack \
python2-colorama \
python2-configobj \
python2-eyed3 \
python2-pyspotify \
python2-service-identity \
python-distutils-extra \
python-proboscis \
python-pycryptodomex \
qjackctl \
redshift \
remarkable \
rfkill \
rhythmbox \
robomongo \
ruby-sass \
scons \
setconf \
sharutils \
simple-scan \
skypeforlinux-bin \
spectacle \
spotify \
steam \
steam-fonts \
streamstudio-bin \
stress \
swig \
thermald \
thunderbird \
transmission-gtk \
unified-remote-server \
upx \
vagrant \
vala \
valgrind \
virtualbox-ext-oracle \
vmware-systemd-services \
w3m \
weston \
xcftools \
xdg-desktop-portal \
xf86-input-evdev \
xf86-input-synaptics \
xf86-input-vmmouse \
xf86-input-void \
xf86-video-ati \
xf86-video-dummy \
xf86-video-fbdev \
xf86-video-intel \
xf86-video-nouveau \
xf86-video-openchrome \
xf86-video-vesa \
xf86-video-voodoo \
xfburn \
xfce4-appfinder \
xfce4-artwork \
xfce4-battery-plugin \
xfce4-clipman-plugin \
xfce4-cpufreq-plugin \
xfce4-cpugraph-plugin \
xfce4-datetime-plugin \
xfce4-dev-tools \
xfce4-dict \
xfce4-diskperf-plugin \
xfce4-eyes-plugin \
xfce4-fsguard-plugin \
xfce4-genmon-plugin \
xfce4-mailwatch-plugin \
xfce4-mount-plugin \
xfce4-mpc-plugin \
xfce4-netload-plugin \
xfce4-notes-plugin \
xfce4-power-manager \
xfce4-pulseaudio-plugin \
xfce4-screenshooter \
xfce4-sensors-plugin \
xfce4-session \
xfce4-settings \
xfce4-smartbookmark-plugin \
xfce4-systemload-plugin \
xfce4-taskmanager \
xfce4-terminal \
xfce4-time-out-plugin \
xfce4-timer-plugin \
xfce4-verve-plugin \
xfce4-wavelan-plugin \
xfce4-weather-plugin \
xfce4-whiskermenu-plugin \
xfce4-xkb-plugin \
xfdesktop \
xflux \
xfwm4-themes \
xorg-docs \
xorg-fonts-100dpi \
xorg-fonts-75dpi \
xorg-server-xdmx \
xorg-server-xephyr \
xorg-server-xnest \
xorg-server-xvfb \
xorg-server-xwayland \
xorg-sessreg \
xorg-smproxy \
xorg-x11perf \
xorg-xbacklight \
xorg-xcmsdb \
xorg-xcursorgen \
xorg-xdriinfo \
xorg-xev \
xorg-xgamma \
xorg-xhost \
xorg-xinput \
xorg-xkbevd \
xorg-xkbutils \
xorg-xkill \
xorg-xlsatoms \
xorg-xlsclients \
xorg-xpr \
xorg-xrefresh \
xorg-xsetroot \
xorg-xvinfo \
xorg-xwd \
xorg-xwininfo \
xorg-xwud \
xsane \
yaourt-gui \
yasm \
youtube-viewer \
zita-alsa-pcmi \
zsh
